name: 'Update profiles.dev'
description: 'Self-service profile updates for profiles.dev. Requires repository to be named "profiles.dev" and updates via push events only.'
author: 'NomadOps'
branding:
  icon: 'user-check'
  color: 'blue'
inputs:
  api-endpoint:
    description: 'API endpoint for profiles.dev webhook'
    required: false
    default: 'https://api.profiles.dev/api/webhook'
  profile-path:
    description: 'Path to profile.yaml file'
    required: false
    default: 'profile.yaml'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
outputs:
  profile-id:
    description: 'The ID of the updated profile'
  status:
    description: 'Status of the update operation'
  message:
    description: 'Detailed message about the operation'
runs:
  using: 'node20'
  main: 'action/dist/index.js'