name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build action
        run: npm run build
        
      - name: Test action (dry run)
        uses: ./
        with:
          api-endpoint: 'https://httpbin.org/post' # Mock endpoint for testing
          profile-path: 'test/fixtures/profile.yaml'
          debug: 'true'
        continue-on-error: true