name: Update profiles.dev

on:
  push:
    branches: [ main ]
    paths:
      - 'profile.yaml'
  # NOTE: workflow_dispatch is NOT supported by the API
  # Only push events to the default branch are allowed

permissions:
  id-token: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update profiles.dev
        uses: nomadops/profiles.dev@main
        with:
          debug: true
