name: Update profiles.dev

on:
  push:
    branches: [ main ]
    paths:
      - 'profile.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update profiles.dev
        uses: ./  # Will use nomadops/profiles.dev@v1 after testing
        # with:
        #   api-endpoint: 'https://httpbin.org/post'  # Uncomment only for mock testing
        #   debug: true